from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path

try:
    import psycopg
    from psycopg import errors as psycopg_errors
except ImportError:  # PostgreSQL support is optional for SQLite-only tests.
    psycopg = None
    psycopg_errors = None


IntegrityError = (sqlite3.IntegrityError,)
if psycopg_errors is not None:
    IntegrityError = IntegrityError + (psycopg_errors.UniqueViolation, psycopg_errors.ForeignKeyViolation)


def resolve_database_path(database_path, default_path):
    return database_path or os.getenv("DATABASE_URL") or default_path


class _HybridRow(tuple):
    def __new__(cls, values, columns):
        row = super().__new__(cls, values)
        row.columns = columns
        return row

    def __getitem__(self, key):
        if isinstance(key, str):
            return super().__getitem__(self.columns.index(key))
        return super().__getitem__(key)


class _PostgresCursor:
    def __init__(self, cursor):
        self.cursor = cursor

    def _row(self, row):
        if row is None:
            return None
        columns = [column.name for column in self.cursor.description]
        return _HybridRow(row, columns)

    def fetchone(self):
        return self._row(self.cursor.fetchone())

    def fetchall(self):
        return [self._row(row) for row in self.cursor.fetchall()]

    @property
    def lastrowid(self):
        row = self.fetchone()
        return row[0] if row else None


class _PostgresConnection:
    def __init__(self, connection):
        self.connection = connection

    @staticmethod
    def _sql(statement):
        statement = statement.replace("BEGIN IMMEDIATE", "BEGIN")
        statement = statement.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        return re.sub(r"\?", "%s", statement)

    def execute(self, statement, parameters=()):
        cursor = self.connection.execute(self._sql(statement), parameters)
        return _PostgresCursor(cursor)

    def executescript(self, script):
        for statement in script.split(";"):
            if statement.strip():
                self.execute(statement)

    def __enter__(self):
        return self

    def __exit__(self, exception_type, exception, traceback):
        if exception_type:
            self.connection.rollback()
        else:
            self.connection.commit()
        self.connection.close()


class DatabaseConnection:
    def __init__(self, database_path, default_path):
        self.database_path = resolve_database_path(database_path, default_path)
        self.is_postgres = isinstance(self.database_path, str) and self.database_path.startswith(("postgres://", "postgresql://"))

    def connect(self):
        if self.is_postgres:
            if psycopg is None:
                raise RuntimeError("PostgreSQL support requires psycopg[binary]. Install the project requirements first.")
            return _PostgresConnection(psycopg.connect(self.database_path))
        connection = sqlite3.connect(str(self.database_path))
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")
        return connection

    def table_columns(self, connection, table_name):
        if self.is_postgres:
            rows = connection.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = ?",
                (table_name,),
            ).fetchall()
            return {row[0] for row in rows}
        return {row[1] for row in connection.execute(f"PRAGMA table_info({table_name})")}

    def table_exists(self, connection, table_name):
        if self.is_postgres:
            return bool(connection.execute(
                "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ?",
                (table_name,),
            ).fetchone())
        return bool(connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", (table_name,)
        ).fetchone())


def close_connection(connection):
    if hasattr(connection, "connection"):
        connection.connection.close()
    else:
        connection.close()
